feat: add createArena handler
vivendell/arenas-program pull request #2
Opened 2022-01-18 00:47 UTC by mahubgt

Closes #1

2022-01-18 05:37 UTC, eliagoris approved these changes

2022-01-18 05:37 UTC, eliagoris commented
LGTM

2022-01-19 15:18 UTC, lucasig11 requested changes

2022-01-19 15:18 UTC, lucasig11 commented on programs/arenas-program/src/lib.rs
> +        let player_one = &mut ctx.accounts.player_one;
This reference does not need to be mutable.

2022-01-19 15:18 UTC, lucasig11 commented on programs/arenas-program/src/lib.rs
> +    seed: [u8; 8],
The `bump` and `seed` fields are not being used anywhere else after the account initialization, I don't see the need to store those extra 69 bytes inside the account, at least for now (?).

2022-01-20 10:19 UTC, merged